package com.project.bitLabs.enums;

public enum DiplomaSpecialization {
	MECH, CE, EEE, ECE, CSE, AME, CHEM, IT, IE, MINING, METALLURGICAL, AGRI, TEXTILE, INTERIOR_DESIGNING,
	FASHION_DESIGNING, HOTEL_MANAGEMENT, PHARMACY, MLT, RIT;
}
